"name": "Poko",
"version": "1.0.0", 
"description": ":flying_saucer::dizzy: Greetings. My name is Pvokko Reyhan Remnai (Or Poko for short)— a bot invading your atmosphere and learning about your beautiful, green, organic planet. 


:sunny::seedling: I’m able to make server-wide announcements for events on streams, important dates, and the like. The more I learn, the more I’m able to help out, so please look forward to future updates.

:book::sunflower: I really appreciate your time and aid as I learn about your planet and its people. You can ask me any questions while I’m visiting, if you’d like.

Best wishes for you,
Poko. :star2:",
"main": "main.js"
"scripts": { 
  "test": "echo/ "Error: no test spefspecified\"&& exit 1"
}, 
"author": "Apple",
"license": "Apple",
"dependencies": { 
"discord.js": "^12.2.0"
}
}